import type { SantaData } from './ssot';

const realAccounts: SantaData['accounts'] = [
    {
        "id": "acc_688b33996cfdb12dc002971d",
        "name": "Ingo Gestion De Activos S.L.",
        "cif": "B50831429",
        "type": "HORECA",
        "stage": "POTENCIAL",
        "ownerId": "u_martin",
        "billerId": "SB",
        "address": "Paseo Idependencia 32 5ºC",
        "city": "ZARAGOZA",
        "country": "ES",
        "phone": undefined,
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_688b34057632f67a690280cc",
        "name": "Quirites Inmobiliaria S.L",
        "cif": "B82383837",
        "type": "HORECA",
        "stage": "POTENCIAL",
        "ownerId": "u_martin",
        "billerId": "SB",
        "address": "Calle Rafael Calvo 15.",
        "city": "Madrid",
        "country": "ES",
        "phone": undefined,
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_68bb06b601e0f7c63106f9c0",
        "name": "Holded",
        "cif": undefined,
        "type": "PROVEEDOR",
        "stage": "CERRADA",
        "ownerId": "u_admin",
        "billerId": "SB",
        "address": undefined,
        "city": undefined,
        "country": "ES",
        "phone": undefined,
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_68c145450e154f31da0a635a",
        "name": "Real Club de Golf Sotogrande",
        "cif": "G11048212",
        "type": "HORECA",
        "stage": "POTENCIAL",
        "ownerId": "u_martin",
        "billerId": "SB",
        "address": "Paseo del Parque s/n",
        "city": "Sogrande",
        "country": "ES",
        "phone": undefined,
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_68c3a83f6fc6d205da090a1c",
        "name": "Goya vinos y viñedos",
        "cif": "B50934322",
        "type": "HORECA",
        "stage": "POTENCIAL",
        "ownerId": "u_martin",
        "billerId": "SB",
        "address": "C/Taernto Nave 6 Poligo Plaza Parce Ali 4",
        "city": "Zaraogza",
        "country": "ES",
        "phone": undefined,
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_68c3aacb908a3473690fb542",
        "name": "Devins Menorca S.L.",
        "cif": "B57075665",
        "type": "HORECA",
        "stage": "POTENCIAL",
        "ownerId": "u_martin",
        "billerId": "SB",
        "address": "Cami de Ses Vinyes",
        "city": "Maó-Mahón",
        "country": "ES",
        "phone": undefined,
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_68c3b1c18c6144516104fca0",
        "name": "Importaciones Cuesta S.L.",
        "cif": "B33015520",
        "type": "DISTRIBUIDOR",
        "stage": "POTENCIAL",
        "ownerId": "u_martin",
        "billerId": "SB",
        "address": "Polígono Industrial: “Las Nieves” C/ Puerto de Guadarrama, 28",
        "city": "Móstoles",
        "country": "ES",
        "phone": undefined,
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_68c7ec9926a04d5b3907d2ef",
        "name": "Lucia Coldculture",
        "cif": "17453120F",
        "type": "HORECA",
        "stage": "POTENCIAL",
        "ownerId": "u_martin",
        "billerId": "SB",
        "address": undefined,
        "city": undefined,
        "country": "ES",
        "phone": undefined,
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_68c82416918208024a0a5be9",
        "name": "DE JUAN BOSCO CARDENAS CAMPS",
        "cif": "49962131J",
        "type": "PROVEEDOR",
        "stage": "CERRADA",
        "ownerId": "u_admin",
        "billerId": "SB",
        "address": undefined,
        "city": "Madrid",
        "country": "ES",
        "phone": undefined,
        "createdAt": "2024-01-01T00:00:00.000Z"
    }
];


// --- Full SSOT Mock Object ---
export const realSantaData: SantaData = {
  users: [],
  accounts: realAccounts,
  products: [],
  materials: [],
  distributors: [],
  interactions: [],
  ordersSellOut: [],
  shipments: [],
  lots: [],
  inventory: [],
  stockMoves: [],
  receipts: [],
  purchaseOrders: [],
  billOfMaterials: [],
  productionOrders: [],
  qaChecks: [],
  suppliers: [],
  traceEvents: [],
  goodsReceipts: [],
  mktEvents: [],
  onlineCampaigns: [],
  activations: [],
  creators: [],
  influencerCollabs: [],
  priceLists: [],
  nonConformities: [],
  supplierBills: [],
  payments: [],
  batches: [],
  packRuns: [],
  trace: [],
  qcTests: [],
};
