
import type { SantaData } from './ssot';

const realAccounts: SantaData['accounts'] = [
    {
        "id": "acc_11",
        "name": "Sabodiga",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_divins",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_12",
        "name": "Senor Bigote",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_divins",
        "mainContactName": "Jesus",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_13",
        "name": "Cristanal y Gadinat",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_divins",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_14",
        "name": "Oysters",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_divins",
        "mainContactName": "Tobi",
        "address": "Carrer de Bastió, 7, 07703 Maó, Illes Balears",
        "tags": ["colocacion", "plv"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_15",
        "name": "Sa Tintina",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_divins",
        "mainContactName": "Alex",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_16",
        "name": "Aqui hay Tomate",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_divins",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_17",
        "name": "Cova den Xoroi",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_divins",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_18",
        "name": "Madrid al Cielo",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_divins",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_19",
        "name": "Bar Augustin",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_divins",
        "mainContactName": "Patri",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_20",
        "name": "Supermercado melo",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_21",
        "name": "Cervecería Santa Barbara",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Álvaro",
        "tags": ["colocacion", "plv"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_22",
        "name": "Catering the cook",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Silvia Lodares",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_23",
        "name": "Bulo",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Manu Cabello",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_24",
        "name": "Joselito",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "mainContactName": "Carlos y jose Gómez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_25",
        "name": "Adrede",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "mainContactName": "Angel",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_26",
        "name": "Las tablas",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Borja",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_27",
        "name": "Gabys Bagels",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Baby y Rafa",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_28",
        "name": "Delirium",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Lu",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_29",
        "name": "Terraza campo del moro",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Luna",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_30",
        "name": "Abacería Macarena",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Luis Magaña",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_31",
        "name": "Asador Galino Pueyo",
        "city": "Zaragoza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_martin",
        "billerId": "d_goya",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_32",
        "name": "Alacena de Aragón",
        "city": "Zaragoza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_martin",
        "billerId": "d_goya",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_33",
        "name": "Gayarre",
        "city": "Zaragoza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_martin",
        "billerId": "d_goya",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_34",
        "name": "Mantequerias Sanz",
        "city": "Zaragoza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_martin",
        "billerId": "d_goya",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_35",
        "name": "Resaurante 1885",
        "city": "Zaragoza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_nico",
        "billerId": "d_goya",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_36",
        "name": "La embajada",
        "city": "Zaragoza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_nico",
        "billerId": "d_goya",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_37",
        "name": "La clandestina",
        "city": "Zaragoza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_nico",
        "billerId": "d_goya",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_38",
        "name": "Tiare Beach Club",
        "city": "Girona",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_aral",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_39",
        "name": "Stop Supermercado",
        "city": "Ibiza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_nico",
        "billerId": "d_isbiza",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_40",
        "name": "Flahertys",
        "city": "Ibiza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_isbiza",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_41",
        "name": "Roto Zaragoza",
        "city": "Zaragoza",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_goya",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_42",
        "name": "Roto Formigual",
        "city": "Zaragoza",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_goya",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_43",
        "name": "Tulp",
        "city": "Ibiza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_nico",
        "billerId": "d_isbiza",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_44",
        "name": "La Bicicleta Roja",
        "city": "Mallorca",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_ismallorca",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_45",
        "name": "Lanteo",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Berni Landeta",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_46",
        "name": "Taberna Pedraza",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Santigo Pedraza",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_47",
        "name": "Rel Club de Golf Sotogrande",
        "city": "Anadalucía",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "SB",
        "mainContactName": "Kostka",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_48",
        "name": "Pecaditos",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Alberto Sancho",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_49",
        "name": "Chez Pepito",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Romin",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_50",
        "name": "Burdel de Foc",
        "city": "Menorca",
        "type": "HORECA",
        "stage": "POTENCIAL",
        "ownerId": "u_nico",
        "billerId": "d_divins",
        "mainContactName": "Fran",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_51",
        "name": "Filemon",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_52",
        "name": "La Rubia",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Nene",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_53",
        "name": "Grupo dejate llevar",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Guiller Bragado",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_54",
        "name": "Las Terrazas",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "El patillas",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_55",
        "name": "Richelieu",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Juanjo",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_56",
        "name": "Grupo Dani García",
        "city": "Madrid, Anadalucía",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "SB",
        "mainContactName": "Dani García",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_57",
        "name": "Corte Inglés",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Marta Álvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_58",
        "name": "Marea",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Alex",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_59",
        "name": "Grupo Paladium",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Dani Sakovic Matutes",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_60",
        "name": "Catering Samantha",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "mainContactName": "Samantha",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_61",
        "name": "Varma",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_62",
        "name": "Grupo Triciclo",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_63",
        "name": "Grupo Mentidero",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_64",
        "name": "Palacio de Alcala",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_65",
        "name": "Golda",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_66",
        "name": "Casa Ortega",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "mainContactName": "Gonzalo Ortega",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_67",
        "name": "Mantequerias Bravo",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_68",
        "name": "Nueva Taberna",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_69",
        "name": "La maquina Jorge Juan",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_70",
        "name": "Costa Este",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Roberto compras",
        "phone": "635139463",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_71",
        "name": "Hotel Welington",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_72",
        "name": "Trocadero",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": [],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_73",
        "name": "Trocadero",
        "city": "Malaga",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "SB",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_74",
        "name": "Fondeo",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_75",
        "name": "El Enemigo",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_76",
        "name": "Copa de Balón",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_77",
        "name": "Ana Rey Catering y tienda",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_78",
        "name": "Wondermarket. Keila",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_79",
        "name": "Catering Laurel",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_80",
        "name": "Sea Beach",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Cristina Losada",
        "phone": "687004187",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_81",
        "name": "Grupo Hyatt",
        "city": "Mallorca",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_ismallorca",
        "mainContactName": "Rubén Ubric",
        "phone": "679856568",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_82",
        "name": "AN Group",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Carlos Conde",
        "phone": "658400758",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_83",
        "name": "Kiss chupitos",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "selim",
        "phone": "633336625",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_84",
        "name": "Bokaxankla:",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_85",
        "name": "Trompo",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_86",
        "name": "Florida Park",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_87",
        "name": "Bajío",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_88",
        "name": "La Boheme",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_89",
        "name": "Los Peñotes",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_90",
        "name": "Ciboulet",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_91",
        "name": "NH",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_92",
        "name": "AC",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_93",
        "name": "Café de París",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_94",
        "name": "Bar Nuevo M40",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_95",
        "name": "Noname",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_96",
        "name": "Liquor Store",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_97",
        "name": "Fuerte Group Hotels",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_98",
        "name": "4 Latas",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_99",
        "name": "new Orleans",
        "city": "Anadalucía",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "SB",
        "mainContactName": "Rubén",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_100",
        "name": "Boca Grande",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "d_alvarez",
        "mainContactName": "Salvador Fernández",
        "phone": "627904317",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_101",
        "name": "Boca Grande",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Salvador Fernández",
        "phone": "627904317",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_102",
        "name": "Boca Chica",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Salvador Fernández",
        "phone": "627904317",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_103",
        "name": "Chica Club",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Salvador Fernández",
        "phone": "627904317",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_104",
        "name": "Chica Beach",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Salvador Fernández",
        "phone": "627904317",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_105",
        "name": "Grupo Boia",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Manel Vheli",
        "phone": "622125060",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_106",
        "name": "candestino",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Raul",
        "phone": "665763478",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_107",
        "name": "el centro cultural",
        "city": "Girona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_aral",
        "mainContactName": "Guillermo Martínez",
        "phone": "642198562",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_108",
        "name": "La Penela",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_109",
        "name": "Aurea",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_110",
        "name": "Akangas",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_111",
        "name": "Cafe Pino",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_112",
        "name": "Ke Sotogrande",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_113",
        "name": "Formage",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "mainContactName": "Adrian Pellejo",
        "phone": "647193284",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_114",
        "name": "Supernormal",
        "city": "Anadalucía",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_alfonso",
        "billerId": "SB",
        "mainContactName": "Chiara",
        "mainContactEmail": "adrian@formage.com",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_115",
        "name": "Vinology",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "mainContactName": "Somelier Mateo",
        "phone": "915272066",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_116",
        "name": "Ingo",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "mainContactName": "Cajas",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_117",
        "name": "El Enemigo tienda",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "mainContactName": "Juan Ortiz",
        "tags": ["colocacion", "plv"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_118",
        "name": "100% Mexico",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_martin",
        "billerId": "d_alvarez",
        "mainContactName": "Jordi",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_119",
        "name": "eMeBe",
        "city": "Madrid",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_nico",
        "billerId": "d_alvarez",
        "mainContactName": "Miguel",
        "tags": ["colocacion", "plv"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_120",
        "name": "diene",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Javier nieto",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_121",
        "name": "jane",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Joan",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_122",
        "name": "sea sea beach",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Ignacio furest",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_123",
        "name": "sls",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "mateo jefe de bebidas",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_124",
        "name": "rosalia",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_125",
        "name": "cooper",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "edir malpartida",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_126",
        "name": "catering stan",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Stanley",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_127",
        "name": "catering la lloca",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_128",
        "name": "la dama",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "POTENCIAL",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Andrea Civetinni",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_129",
        "name": "feroz",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "POTENCIAL",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "aritz",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_130",
        "name": "vinalium",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "mery",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_131",
        "name": "bn group",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Cristian valls",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_132",
        "name": "shoko",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "David",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_133",
        "name": "grupo Isabela",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_134",
        "name": "grupo confitería",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "marc",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_135",
        "name": "vila viniteca",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Albert",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_136",
        "name": "the green dog",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Raul",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_137",
        "name": "clandestino",
        "city": "Barcelona",
        "type": "HORECA",
        "stage": "SEGUIMIENTO",
        "ownerId": "u_patxi",
        "billerId": "d_escola",
        "mainContactName": "Raul",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_138",
        "name": "coctel sunsrise",
        "city": "Girona",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_aral",
        "mainContactName": "gerard",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_139",
        "name": "santeria",
        "city": "Ibiza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_isbiza",
        "mainContactName": "albert",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    },
    {
        "id": "acc_140",
        "name": "tienda stoo",
        "city": "Ibiza",
        "type": "HORECA",
        "stage": "ACTIVA",
        "ownerId": "u_patxi",
        "billerId": "d_isbiza",
        "mainContactName": "albert",
        "tags": ["colocacion"],
        "createdAt": "2024-01-01T00:00:00.000Z"
    }
];


// --- Full SSOT Mock Object ---
export const realSantaData: SantaData = {
  users: [],
  accounts: realAccounts,
  products: [],
  materials: [],
  distributors: [],
  interactions: [],
  ordersSellOut: [],
  shipments: [],
  lots: [],
  inventory: [],
  stockMoves: [],
  receipts: [],
  purchaseOrders: [],
  billOfMaterials: [],
  productionOrders: [],
  qaChecks: [],
  suppliers: [],
  traceEvents: [],
  goodsReceipts: [],
  mktEvents: [],
  onlineCampaigns: [],
  activations: [],
  creators: [],
  influencerCollabs: [],
  priceLists: [],
  nonConformities: [],
  supplierBills: [],
  payments: [],
  batches: [],
  packRuns: [],
  trace: [],
  qcTests: [],
};
