// src/components/admin/EditableCollectionTable.tsx
"use client";

import React, { useState } from 'react';
import { Edit2, Check, X } from 'lucide-react';

interface EditableCollectionTableProps {
  collectionName: string;
  records: any[];
  metadata: Array<{
    recordIndex: number;
    autoGenerated: string[];
    fromOriginal: string[];
    missingRequired: string[];
  }>;
  onUpdate: (collectionName: string, updatedRecords: any[]) => void;
}

export function EditableCollectionTable({
  collectionName,
  records,
  metadata,
  onUpdate
}: EditableCollectionTableProps) {
  const [editingCell, setEditingCell] = useState<{row: number; field: string} | null>(null);
  const [editValue, setEditValue] = useState<string>('');
  const [localRecords, setLocalRecords] = useState(records);

  if (!records || records.length === 0) return null;

  // Obtener todas las claves únicas
  const allFields = Array.from(
    new Set(records.flatMap(r => Object.keys(r)))
  );

  const getCellStyle = (rowIndex: number, field: string) => {
    const recordMeta = metadata.find(m => m.recordIndex === rowIndex);
    if (!recordMeta) return '';

    if (recordMeta.missingRequired.includes(field)) {
      return 'bg-red-50 border-red-200 text-red-900';
    }
    if (recordMeta.autoGenerated.includes(field)) {
      return 'bg-green-50 border-green-200 text-green-900';
    }
    if (recordMeta.fromOriginal.includes(field)) {
      return 'bg-blue-50 border-blue-200 text-blue-900';
    }
    return 'bg-zinc-50';
  };

  const startEditing = (rowIndex: number, field: string, currentValue: any) => {
    setEditingCell({ row: rowIndex, field });
    setEditValue(String(currentValue || ''));
  };

  const saveEdit = () => {
    if (!editingCell) return;

    const newRecords = [...localRecords];
    newRecords[editingCell.row] = {
      ...newRecords[editingCell.row],
      [editingCell.field]: editValue
    };
    
    setLocalRecords(newRecords);
    onUpdate(collectionName, newRecords);
    setEditingCell(null);
    setEditValue('');
  };

  const cancelEdit = () => {
    setEditingCell(null);
    setEditValue('');
  };

  const formatValue = (value: any): string => {
    if (value === null || value === undefined) return '';
    if (typeof value === 'object') return JSON.stringify(value);
    return String(value);
  };

  return (
    <div className="mb-6">
      <div className="flex items-center justify-between mb-3">
        <h4 className="font-semibold text-lg">{collectionName}</h4>
        <div className="flex gap-2 text-xs">
          <div className="flex items-center gap-1">
            <div className="w-3 h-3 bg-blue-200 rounded"></div>
            <span>Original</span>
          </div>
          <div className="flex items-center gap-1">
            <div className="w-3 h-3 bg-green-200 rounded"></div>
            <span>Auto-generado</span>
          </div>
          <div className="flex items-center gap-1">
            <div className="w-3 h-3 bg-red-200 rounded"></div>
            <span>Requerido</span>
          </div>
        </div>
      </div>

      <div className="overflow-x-auto border rounded-lg">
        <table className="min-w-full text-sm">
          <thead className="bg-zinc-100">
            <tr>
              <th className="px-3 py-2 text-left text-xs font-semibold text-zinc-700 sticky left-0 bg-zinc-100">
                #
              </th>
              {allFields.map(field => (
                <th
                  key={field}
                  className="px-3 py-2 text-left text-xs font-semibold text-zinc-700 whitespace-nowrap"
                >
                  {field}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {localRecords.map((record, rowIndex) => (
              <tr key={rowIndex} className="border-t hover:bg-zinc-50">
                <td className="px-3 py-2 text-xs font-medium text-zinc-500 sticky left-0 bg-white">
                  {rowIndex + 1}
                </td>
                {allFields.map(field => {
                  const isEditing = editingCell?.row === rowIndex && editingCell?.field === field;
                  const value = record[field];
                  const cellStyle = getCellStyle(rowIndex, field);
                  const recordMeta = metadata.find(m => m.recordIndex === rowIndex);
                  const isMissing = recordMeta?.missingRequired.includes(field);

                  return (
                    <td
                      key={field}
                      className={`px-3 py-2 text-xs border-l ${cellStyle} relative group`}
                    >
                      {isEditing ? (
                        <div className="flex items-center gap-1">
                          <input
                            type="text"
                            value={editValue}
                            onChange={(e) => setEditValue(e.target.value)}
                            className="w-full px-2 py-1 text-xs border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                            autoFocus
                            onKeyDown={(e) => {
                              if (e.key === 'Enter') saveEdit();
                              if (e.key === 'Escape') cancelEdit();
                            }}
                          />
                          <button
                            onClick={saveEdit}
                            className="p-1 text-green-600 hover:bg-green-100 rounded"
                          >
                            <Check className="h-3 w-3" />
                          </button>
                          <button
                            onClick={cancelEdit}
                            className="p-1 text-red-600 hover:bg-red-100 rounded"
                          >
                            <X className="h-3 w-3" />
                          </button>
                        </div>
                      ) : (
                        <div className="flex items-center justify-between group">
                          <span className={`truncate max-w-xs ${!value && isMissing ? 'text-red-500 italic' : ''}`}>
                            {!value && isMissing ? 'Falta dato requerido' : formatValue(value)}
                          </span>
                          {isMissing && (
                            <button
                              onClick={() => startEditing(rowIndex, field, value)}
                              className="ml-2 p-1 opacity-0 group-hover:opacity-100 text-blue-600 hover:bg-blue-100 rounded transition-opacity"
                              title="Editar campo requerido"
                            >
                              <Edit2 className="h-3 w-3" />
                            </button>
                          )}
                        </div>
                      )}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Resumen de la colección */}
      <div className="mt-2 text-xs text-zinc-600">
        <span className="font-medium">{localRecords.length}</span> registros
        {metadata.some(m => m.missingRequired.length > 0) && (
          <span className="ml-4 text-red-600 font-medium">
            ⚠️ Hay campos requeridos sin completar
          </span>
        )}
      </div>
    </div>
  );
}
