// src/app/api/process-excel/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

interface ProcessExcelRequest {
  sheets: Record<string, any[]>; // { "users": [...], "accounts": [...], ... }
}

interface ProcessExcelResponse {
  collections: Record<string, any[]>; // Colecciones completas listas para importar
  metadata: Record<string, Array<{
    recordIndex: number;
    autoGenerated: string[]; // Campos generados por IA
    fromOriginal: string[]; // Campos del Excel original
    missingRequired: string[]; // Campos requeridos que faltan
  }>>;
  analysis: {
    sheetsProcessed: string[];
    collectionsGenerated: string[];
    relationshipsDetected: Array<{
      from: string;
      to: string;
      field: string;
    }>;
  };
  warnings: Array<{
    severity: 'error' | 'warning' | 'info';
    message: string;
    affectedRecords?: number;
  }>;
  missingInformation: Array<{
    collection: string;
    field: string;
    reason: string;
    exampleValue?: string;
  }>;
  summary: string;
}

const SSOT_CONTEXT = `
# SSOT (Single Source of Truth) - Estructura del ERP Santa Brisa

## Colecciones Principales:

### 1. users
- id, name, email, role (comercial|admin|ops|owner), active
- Usuarios y comerciales del sistema

### 2. parties  
- id, name, kind (ORG|PERSON), roles (array: DISTRIBUTOR, CUSTOMER, etc)
- legalName, vat, billingAddress, shippingAddress, emails, phones, people
- Entidades jurídicas (distribuidores, clientes)

### 3. partyRoles ⭐ CRÍTICO
- id, partyId, userId, role (SALESPERSON), isActive
- Vincula comerciales con distribuidores

### 4. accounts
- id, name, partyId, segment (HORECA|RETAIL|ONLINE|PRIVADA|DISTRIBUIDOR)
- stage (POTENCIAL|ACTIVA|SEGUIMIENTO|FALLIDA)
- flow (PLACEMENT|DIRECT), ownerId, distributorPartyId
- aliases (array para fuzzy matching)
- Cuentas comerciales

### 5. ordersSellOut
- id, accountId, orderDate, totalAmount, status, flow, lines
- Pedidos de venta

### 6. items
- id, sku, name, category, uom, priceList, unitsPerCase
- Productos

## Reglas Críticas:
1. Si Account tiene flow=PLACEMENT → DEBE tener distributorPartyId
2. Si Account tiene flow=DIRECT → NO debe tener distributorPartyId
3. Todos los IDs deben seguir patrón: acc_, party_, us_, etc
4. Generar aliases automáticamente para fuzzy matching
5. Normalizar SIEMPRE: "horeca" → "HORECA", "activa" → "ACTIVA"
6. Crear party para cada cuenta si no existe
7. Crear partyRole para vincular comercial con distribuidor
`;

export async function POST(req: NextRequest) {
  try {
    const body: ProcessExcelRequest = await req.json();
    const { sheets } = body;

    if (!sheets || typeof sheets !== 'object') {
      return NextResponse.json(
        { error: 'Se requiere un objeto con las hojas del Excel' },
        { status: 400 }
      );
    }

    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');
    const model = genAI.getGenerativeModel({ 
      model: 'gemini-2.0-flash',
      generationConfig: {
        temperature: 0.1,
        responseMimeType: "application/json", // FORZAR JSON válido
      }
    });

    // Construir prompt simplificado
    const prompt = `Procesa este Excel y genera colecciones para el ERP.

${SSOT_CONTEXT}

DATOS:
${JSON.stringify(sheets, null, 2)}

TAREAS:
1. Analizar hojas y crear colecciones: users, parties, partyRoles, accounts, ordersSellOut, items
2. Generar IDs (us_, acc_, party_), aliases, fechas ISO
3. Normalizar enums a MAYÚSCULAS
4. Crear party por cada account
5. Crear partyRoles para comerciales-distribuidores

RESPONDE JSON VÁLIDO:
{
  "metadata": {"collectionName": [{"recordIndex": 0, "autoGenerated": ["id"], "fromOriginal": ["name"], "missingRequired": []}]},
  "collections": {"collectionName": [{"id": "value"}]},
  "analysis": {"sheetsProcessed": [], "collectionsGenerated": [], "relationshipsDetected": []},
  "warnings": [],
  "missingInformation": [],
  "summary": "texto"
}`;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text();
    
    console.log('Respuesta de Gemini (primeros 500 chars):', responseText.substring(0, 500));
    
    // Extraer JSON más robusto
    let jsonText = responseText;
    
    // Quitar markdown si existe
    const jsonMatch = responseText.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
    if (jsonMatch) {
      jsonText = jsonMatch[1];
    } else {
      // Buscar el primer { hasta el último }
      const start = responseText.indexOf('{');
      const end = responseText.lastIndexOf('}');
      if (start !== -1 && end !== -1) {
        jsonText = responseText.substring(start, end + 1);
      }
    }
    
    // Intentar parsear
    let processedData: ProcessExcelResponse;
    try {
      processedData = JSON.parse(jsonText);
    } catch (parseError) {
      console.error('Error parseando JSON:', parseError);
      console.error('JSON que falló:', jsonText.substring(0, 1000));
      throw new Error(`JSON inválido de Gemini: ${parseError instanceof Error ? parseError.message : 'Error desconocido'}`);
    }

    return NextResponse.json(processedData);
  } catch (error) {
    console.error('Error al procesar Excel:', error);
    return NextResponse.json(
      { 
        error: 'Error al procesar Excel con IA',
        details: error instanceof Error ? error.message : 'Error desconocido'
      },
      { status: 500 }
    );
  }
}
