// src/app/(app)/admin/excel-import/page.tsx
"use client";

import React, { useState } from 'react';
import { Upload, FileSpreadsheet, AlertCircle, CheckCircle, Sparkles, Download } from 'lucide-react';
import { toast } from 'sonner';
import { SBButton } from '@/components/ui';
import { useData } from '@/lib/dataprovider';
import * as XLSX from 'xlsx';
import { EditableCollectionTable } from '@/components/admin/EditableCollectionTable';

interface ProcessedData {
  collections: Record<string, any[]>;
  metadata: Record<string, Array<{
    recordIndex: number;
    autoGenerated: string[];
    fromOriginal: string[];
    missingRequired: string[];
  }>>;
  analysis: {
    sheetsProcessed: string[];
    collectionsGenerated: string[];
    relationshipsDetected: Array<{
      from: string;
      to: string;
      field: string;
    }>;
  };
  warnings: Array<{
    severity: 'error' | 'warning' | 'info';
    message: string;
    affectedRecords?: number;
  }>;
  missingInformation: Array<{
    collection: string;
    field: string;
    reason: string;
    exampleValue?: string;
  }>;
  summary: string;
}

export default function ExcelImportPage() {
  const [file, setFile] = useState<File | null>(null);
  const [processing, setProcessing] = useState(false);
  const [importing, setImporting] = useState(false);
  const [processedData, setProcessedData] = useState<ProcessedData | null>(null);
  const [editedCollections, setEditedCollections] = useState<Record<string, any[]>>({});
  const { saveAllCollections } = useData();

  const handleCollectionUpdate = (collectionName: string, updatedRecords: any[]) => {
    setEditedCollections(prev => ({
      ...prev,
      [collectionName]: updatedRecords
    }));
  };

  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0];
    if (!selectedFile) return;

    if (!selectedFile.name.endsWith('.xlsx') && !selectedFile.name.endsWith('.xls')) {
      toast.error('Por favor selecciona un archivo Excel (.xlsx o .xls)');
      return;
    }

    setFile(selectedFile);
    setProcessedData(null);
    toast.success(`Archivo ${selectedFile.name} cargado`);
  };

  const handleProcessExcel = async () => {
    if (!file) return;

    setProcessing(true);
    try {
      // Leer el archivo Excel
      const data = await file.arrayBuffer();
      const workbook = XLSX.read(data);

      // Convertir todas las hojas a JSON
      const sheets: Record<string, any[]> = {};
      workbook.SheetNames.forEach(sheetName => {
        const worksheet = workbook.Sheets[sheetName];
        sheets[sheetName] = XLSX.utils.sheet_to_json(worksheet);
      });

      toast.info(`Procesando ${Object.keys(sheets).length} hojas con IA...`);

      // Enviar al endpoint para procesar con Gemini
      const response = await fetch('/api/process-excel', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sheets })
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.details || 'Error al procesar Excel');
      }

      const result: ProcessedData = await response.json();
      setProcessedData(result);

      const errorCount = result.warnings?.filter(w => w.severity === 'error').length || 0;
      if (errorCount > 0) {
        toast.error(`${errorCount} errores encontrados. Revisa los datos.`);
      } else {
        toast.success('✨ Excel procesado correctamente con IA');
      }
    } catch (error) {
      console.error(error);
      toast.error('Error al procesar Excel: ' + (error instanceof Error ? error.message : 'Error desconocido'));
    } finally {
      setProcessing(false);
    }
  };

  const handleImport = async () => {
    if (!processedData) return;

    setImporting(true);
    try {
      // Usar las colecciones editadas si existen, si no las originales
      const collectionsToImport = { ...processedData.collections, ...editedCollections };
      await saveAllCollections(collectionsToImport);
      
      const totalRecords = Object.values(processedData.collections)
        .reduce((sum, col) => sum + col.length, 0);
      
      toast.success(`✅ ${totalRecords} registros importados en ${Object.keys(processedData.collections).length} colecciones`);
      
      // Limpiar
      setFile(null);
      setProcessedData(null);
      
      // Recargar
      setTimeout(() => window.location.reload(), 1500);
    } catch (error) {
      console.error(error);
      toast.error('Error al importar datos');
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="min-h-screen bg-zinc-50 p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <Sparkles className="h-8 w-8 text-purple-600" />
            <h1 className="text-3xl font-bold text-zinc-900">
              Importación Inteligente con IA
            </h1>
          </div>
          <p className="text-zinc-600">
            Sube tu Excel y la IA completará automáticamente todas las colecciones necesarias
          </p>
        </div>

        {/* Paso 1: Subir Excel */}
        <div className="bg-white rounded-xl border p-6 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <div className="flex items-center justify-center w-8 h-8 rounded-full bg-purple-100 text-purple-700 font-semibold">
              1
            </div>
            <h2 className="text-xl font-semibold">Subir Excel</h2>
          </div>

          <div className="border-2 border-dashed border-zinc-300 rounded-lg p-8 text-center">
            <FileSpreadsheet className="h-12 w-12 text-zinc-400 mx-auto mb-4" />
            <p className="text-zinc-600 mb-4">
              Sube un archivo Excel con tus datos (usuarios, cuentas, pedidos, etc.)
            </p>
            <input
              type="file"
              accept=".xlsx,.xls"
              onChange={handleFileSelect}
              className="hidden"
              id="excel-upload"
            />
            <label htmlFor="excel-upload" className="inline-block cursor-pointer">
              <div className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors flex items-center gap-2 font-medium">
                <Upload className="h-4 w-4" />
                <span>Seleccionar Excel</span>
              </div>
            </label>
            {file && (
              <div className="mt-4 flex items-center justify-center gap-2 text-green-700">
                <CheckCircle className="h-5 w-5" />
                <span className="font-medium">{file.name}</span>
              </div>
            )}
          </div>

          {file && !processedData && (
            <div className="mt-4 flex justify-end">
              <SBButton
                size="md"
                variant="primary"
                onClick={handleProcessExcel}
                disabled={processing}
              >
                {processing ? (
                  <>
                    <Sparkles className="h-4 w-4 animate-spin" />
                    Procesando con IA...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" />
                    Procesar con IA
                  </>
                )}
              </SBButton>
            </div>
          )}
        </div>

        {/* Paso 2: Resultado del Procesamiento */}
        {processedData && (
          <>
            {/* Summary */}
            <div className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-xl border border-purple-200 p-6 mb-6">
              <div className="flex items-start gap-3">
                <Sparkles className="h-6 w-6 text-purple-600 flex-shrink-0 mt-1" />
                <div>
                  <h3 className="font-semibold text-lg mb-2">Resumen del Procesamiento</h3>
                  <p className="text-zinc-700">{processedData.summary}</p>
                </div>
              </div>
            </div>

            {/* Analysis */}
            <div className="bg-white rounded-xl border p-6 mb-6">
              <h3 className="font-semibold text-lg mb-4">📊 Análisis</h3>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                <div className="bg-blue-50 rounded-lg p-4">
                  <div className="text-sm text-blue-600 font-medium mb-1">Hojas Procesadas</div>
                  <div className="text-2xl font-bold text-blue-900">
                    {processedData.analysis.sheetsProcessed.length}
                  </div>
                  <div className="text-xs text-blue-600 mt-2">
                    {processedData.analysis.sheetsProcessed.join(', ')}
                  </div>
                </div>

                <div className="bg-green-50 rounded-lg p-4">
                  <div className="text-sm text-green-600 font-medium mb-1">Colecciones Generadas</div>
                  <div className="text-2xl font-bold text-green-900">
                    {processedData.analysis.collectionsGenerated.length}
                  </div>
                  <div className="text-xs text-green-600 mt-2">
                    {processedData.analysis.collectionsGenerated.join(', ')}
                  </div>
                </div>

                <div className="bg-purple-50 rounded-lg p-4">
                  <div className="text-sm text-purple-600 font-medium mb-1">Relaciones Detectadas</div>
                  <div className="text-2xl font-bold text-purple-900">
                    {processedData.analysis.relationshipsDetected.length}
                  </div>
                </div>
              </div>

              {/* Relationships */}
              {processedData.analysis.relationshipsDetected.length > 0 && (
                <div className="mt-4">
                  <h4 className="font-medium mb-2">🔗 Relaciones Entre Entidades:</h4>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                    {processedData.analysis.relationshipsDetected.map((rel, i) => (
                      <div key={i} className="bg-zinc-50 rounded p-3 text-sm">
                        <span className="font-medium">{rel.from}</span>
                        <span className="text-zinc-500 mx-2">→</span>
                        <span className="font-medium">{rel.to}</span>
                        <span className="text-zinc-400 ml-2">({rel.field})</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Collections Tables - Editable */}
            <div className="bg-white rounded-xl border p-6 mb-6">
              <h3 className="font-semibold text-lg mb-4">📊 Tablas Editables por Colección</h3>
              <p className="text-sm text-zinc-600 mb-6">
                Revisa y edita los datos. Los campos en <span className="text-red-600 font-medium">rojo</span> son requeridos y necesitan tu atención.
              </p>
              
              {Object.entries(processedData.collections).map(([collectionName, records]) => (
                <EditableCollectionTable
                  key={collectionName}
                  collectionName={collectionName}
                  records={editedCollections[collectionName] || records}
                  metadata={processedData.metadata?.[collectionName] || []}
                  onUpdate={handleCollectionUpdate}
                />
              ))}
            </div>

            {/* Warnings */}
            {processedData.warnings.length > 0 && (
              <div className="bg-white rounded-xl border p-6 mb-6">
                <h3 className="font-semibold text-lg mb-4">⚠️ Avisos</h3>
                <div className="space-y-2">
                  {processedData.warnings.map((warning, i) => (
                    <div
                      key={i}
                      className={`p-3 rounded-lg border ${
                        warning.severity === 'error'
                          ? 'bg-red-50 border-red-200'
                          : warning.severity === 'warning'
                          ? 'bg-yellow-50 border-yellow-200'
                          : 'bg-blue-50 border-blue-200'
                      }`}
                    >
                      <div className="flex items-start gap-2">
                        <AlertCircle
                          className={`h-5 w-5 flex-shrink-0 ${
                            warning.severity === 'error'
                              ? 'text-red-600'
                              : warning.severity === 'warning'
                              ? 'text-yellow-600'
                              : 'text-blue-600'
                          }`}
                        />
                        <div className="text-sm">
                          <div>{warning.message}</div>
                          {warning.affectedRecords && (
                            <div className="text-xs text-zinc-500 mt-1">
                              Afecta a {warning.affectedRecords} registros
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Missing Information */}
            {processedData.missingInformation.length > 0 && (
              <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-6">
                <div className="flex items-start gap-3 mb-4">
                  <AlertCircle className="h-6 w-6 text-amber-600 flex-shrink-0" />
                  <div>
                    <h3 className="font-semibold text-lg text-amber-900">
                      Información Adicional Necesaria
                    </h3>
                    <p className="text-sm text-amber-700">
                      La IA no pudo completar estos campos y requiere tu input:
                    </p>
                  </div>
                </div>
                <div className="space-y-3">
                  {processedData.missingInformation.map((missing, i) => (
                    <div key={i} className="bg-white rounded-lg p-4 border border-amber-200">
                      <div className="font-medium text-amber-900">
                        {missing.collection} → {missing.field}
                      </div>
                      <div className="text-sm text-amber-700 mt-1">{missing.reason}</div>
                      {missing.exampleValue && (
                        <div className="text-xs text-amber-600 mt-2 font-mono bg-amber-100 px-2 py-1 rounded">
                          Ejemplo: {missing.exampleValue}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Actions */}
            <div className="flex gap-4 justify-end">
              <SBButton
                size="md"
                variant="secondary"
                onClick={() => {
                  setProcessedData(null);
                  setFile(null);
                }}
              >
                Cancelar
              </SBButton>
              <SBButton
                size="md"
                variant="primary"
                onClick={handleImport}
                disabled={
                  importing || 
                  processedData.warnings.some(w => w.severity === 'error') ||
                  Object.values(processedData.metadata || {}).some(metaArray => 
                    metaArray.some(m => m.missingRequired.length > 0)
                  )
                }
              >
                {importing ? (
                  <>
                    <CheckCircle className="h-4 w-4 animate-spin" />
                    Importando...
                  </>
                ) : (
                  <>
                    <CheckCircle className="h-4 w-4" />
                    Importar Todo ({Object.values(processedData.collections).reduce((sum, col) => sum + col.length, 0)} registros)
                  </>
                )}
              </SBButton>
            </div>
          </>
        )}

        {/* Info */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mt-6">
          <div className="flex gap-3">
            <AlertCircle className="h-5 w-5 text-blue-700 flex-shrink-0 mt-0.5" />
            <div className="text-sm text-blue-900">
              <p className="font-semibold mb-2">¿Cómo funciona?</p>
              <ul className="list-disc list-inside space-y-1">
                <li>Sube tu Excel con datos en cualquier formato</li>
                <li>Gemini AI analiza y detecta qué colecciones crear</li>
                <li>Completa automáticamente campos faltantes (IDs, fechas, relaciones)</li>
                <li>Genera aliases para fuzzy matching con Santa Brain</li>
                <li>Crea partyRoles para vincular comerciales con distribuidores</li>
                <li>Te indica qué información adicional necesita si falta algo crítico</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
